 @AbapCatalog.viewEnhancementCategory: [#NONE]
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'cdd'
@Metadata.ignorePropagatedAnnotations: true
@ObjectModel.usageType:{
    serviceQuality: #X,
    sizeCategory: #S,
    dataClass: #MIXED
}
define view entity ZDEMOO as select from I_GLAccountLineItem as Gl
  left outer join ZSD_GSTR1_001 as Gst on Gl.GLAccount = Gst.revenuegl
{
    key Gl.SourceLedger,
    key Gl.CompanyCode,
    key Gl.FiscalYear,
    key Gl.AccountingDocument,
    key Gl.LedgerGLLineItem,
    key Gl.Ledger,
    key Gst.billdoc,
    key Gst.billitm,
    Gl.LedgerFiscalYear,
    Gl.GLRecordType,
    Gl.JrnlEntrAltvFYConsecutiveID,
    Gl.ChartOfAccounts,
    Gl.ControllingArea,
    Gl.FinancialTransactionType,
    Gl.GLBusinessTransactionType,
    Gl.BusinessTransactionCategory,
    Gl.BusinessTransactionType,
    Gl.FinancialClosingStep,
    Gl.ControllingBusTransacType,
    Gl.ReferenceDocumentType,
    Gl.LogicalSystem,
    Gl.ReferenceDocumentContext,
    Gl.ReferenceDocument,
    Gl.ReferenceDocumentItem,
    Gl.ReferenceDocumentItemGroup,
    Gl.TransactionSubitem,
    Gl.OffsettingLedgerGLLineItem,
    Gl.IsReversal,
    Gl.IsReversed,
    Gl.ReversalReferenceDocumentCntxt,
    Gl.ReversalReferenceDocument,
   
    Gst.COCD,
    Gst.DIS,
    Gst.OrginalDocNo,
    Gst.Divb,
    Gst.kunnr,
//    Gst.product,
//    Gst.plant,
    Gst.custname,
    Gst.taxno2,
    Gst.billdate,
    Gst.Curency,
    Gst.tcurr,
    @Semantics.amount.currencyCode: 'tcurr'
    Gst.totnetamt,
    Gst.DISNAME,
    Gst.tottaxamt,
    Gst.excgrate,
    Gst.prdgrp,
    Gst.refdoc,
    Gst.igstrate,
    Gst.igstcurr,
    Gst.cgstrate,
    Gst.sgstRate,
    Gst.CessRate,
    @Semantics.amount.currencyCode: 'tcurr'
    Gst.cgstamt,
    @Semantics.amount.currencyCode: 'tcurr'
    Gst.sgstamt,
    @Semantics.amount.currencyCode: 'tcurr'
    Gst.igstamt,
    @Semantics.amount.currencyCode: 'tcurr'
    Gst.cessamount,
    Gst.itmtxt,
    Gst.uom,
    @Semantics.quantity.unitOfMeasure: 'uom'
    Gst.billqty,
    Gst.hsncode,
    Gst.SupplierGSTIN,
    Gst.State,
    Gst.Divisionb,
//    Gst.ProfitCenter,
    Gst.BillingType,
    Gst.Accdoc,
    Gst.taxno3,
    Gst.billtostate,
    Gst.shiptostate,
    Gst.placeofsupply,
    Gst.OriginalDocumentNumber,
    Gst.invoicedate,
    Gst.invoicecn,
    Gst.revenuegl,
    Gst.subdivision,
    Gst.profitcenter1,
    Gst.profitcenter2,
    Gst.returnperiod,
    Gst.crdrpregst,
    Gst.fidocumentdate,
    Gst.fidocumentno,
    Gst.portcode,
    Gst.shippingbillnumber,
    Gst.shippingbilldate,
    Gst.fob,
    Gst.exportduty,
    Gst.cessratespecific,
    Gst.cessamountspecific,
    Gst.reversechargeflag,
    Gst.tcsflag,
    Gst.ecomgstin,
    Gst.itcflag,
    Gst.reasonforcreditdebitnote,
    Gst.uinorcomposition,
    Gst.supplytype
}

